// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

// GetInviteesStatusEnum - Indicates if the invitee "canceled" or still "active"
type GetInviteesStatusEnum string

const (
	GetInviteesStatusEnumActive   GetInviteesStatusEnum = "active"
	GetInviteesStatusEnumCanceled GetInviteesStatusEnum = "canceled"
)

func (e *GetInviteesStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "active":
		fallthrough
	case "canceled":
		*e = GetInviteesStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GetInviteesStatusEnum: %s", s)
	}
}

type GetInviteesRequest struct {
	// The number of rows to return
	Count *float64 `queryParam:"style=form,explode=true,name=count"`
	// Indicates if the results should be filtered by email address
	Email *string `queryParam:"style=form,explode=true,name=email"`
	// The token to pass to get the next or previous portion of the collection
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Order results by the **created_at** field and direction specified: ascending ("asc") or descending ("desc")
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Indicates if the invitee "canceled" or still "active"
	Status *GetInviteesStatusEnum `queryParam:"style=form,explode=true,name=status"`
	UUID   string                 `pathParam:"style=simple,explode=false,name=uuid"`
}

type GetInvitees403ApplicationJSONMessageEnum string

const (
	GetInvitees403ApplicationJSONMessageEnumYouAreNotAllowedToViewThisEvent GetInvitees403ApplicationJSONMessageEnum = "You are not allowed to view this event"
)

func (e *GetInvitees403ApplicationJSONMessageEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "You are not allowed to view this event":
		*e = GetInvitees403ApplicationJSONMessageEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GetInvitees403ApplicationJSONMessageEnum: %s", s)
	}
}

type GetInvitees403ApplicationJSONTitleEnum string

const (
	GetInvitees403ApplicationJSONTitleEnumPermissionDenied GetInvitees403ApplicationJSONTitleEnum = "Permission Denied"
)

func (e *GetInvitees403ApplicationJSONTitleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Permission Denied":
		*e = GetInvitees403ApplicationJSONTitleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GetInvitees403ApplicationJSONTitleEnum: %s", s)
	}
}

// GetInvitees403ApplicationJSON - Permission Denied
type GetInvitees403ApplicationJSON struct {
	Message *GetInvitees403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *GetInvitees403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type GetInviteesErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetInviteesErrorResponse - Error Object
type GetInviteesErrorResponse struct {
	Details []GetInviteesErrorResponseDetails `json:"details,omitempty"`
	Message string                            `json:"message"`
	Title   string                            `json:"title"`
}

// GetInvitees200ApplicationJSON - Service response
type GetInvitees200ApplicationJSON struct {
	// The set of event invitees matching the criteria
	Collection []shared.Invitee  `json:"collection"`
	Pagination shared.Pagination `json:"pagination"`
}

type GetInviteesResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetInviteesErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetInvitees200ApplicationJSONObject *GetInvitees200ApplicationJSON
	// Permission Denied
	GetInvitees403ApplicationJSONObject *GetInvitees403ApplicationJSON
}
