// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetInviteeNoShowRequest struct {
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type GetInviteeNoShowErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetInviteeNoShowErrorResponse - Error Object
type GetInviteeNoShowErrorResponse struct {
	Details []GetInviteeNoShowErrorResponseDetails `json:"details,omitempty"`
	Message string                                 `json:"message"`
	Title   string                                 `json:"title"`
}

// GetInviteeNoShow200ApplicationJSON - OK
type GetInviteeNoShow200ApplicationJSON struct {
	// Information about an invitees no show.
	Resource shared.InviteeNoShow `json:"resource"`
}

type GetInviteeNoShowResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetInviteeNoShowErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetInviteeNoShow200ApplicationJSONObject *GetInviteeNoShow200ApplicationJSON
}
