// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetMyUserAccountErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetMyUserAccountErrorResponse - Error Object
type GetMyUserAccountErrorResponse struct {
	Details []GetMyUserAccountErrorResponseDetails `json:"details,omitempty"`
	Message string                                 `json:"message"`
	Title   string                                 `json:"title"`
}

// GetMyUserAccount200ApplicationJSON - Service response
type GetMyUserAccount200ApplicationJSON struct {
	// Information about the user.
	Resource shared.User `json:"resource"`
}

type GetMyUserAccountResponse struct {
	ContentType string
	// Cannot authenticate caller
	ErrorResponse *GetMyUserAccountErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetMyUserAccount200ApplicationJSONObject *GetMyUserAccount200ApplicationJSON
}
