// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetOrganizationsUUIDMembershipsRequest struct {
	// The organization membership's unique identifier
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type GetOrganizationsUUIDMembershipsErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetOrganizationsUUIDMembershipsErrorResponse - Error Object
type GetOrganizationsUUIDMembershipsErrorResponse struct {
	Details []GetOrganizationsUUIDMembershipsErrorResponseDetails `json:"details,omitempty"`
	Message string                                                `json:"message"`
	Title   string                                                `json:"title"`
}

// GetOrganizationsUUIDMemberships200ApplicationJSON - OK
type GetOrganizationsUUIDMemberships200ApplicationJSON struct {
	Resource shared.OrganizationMembership `json:"resource"`
}

type GetOrganizationsUUIDMembershipsResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetOrganizationsUUIDMembershipsErrorResponse
	// Caller not authorized to perform this action
	ErrorResponse1 *shared.ErrorResponse
	StatusCode     int
	RawResponse    *http.Response
	// OK
	GetOrganizationsUUIDMemberships200ApplicationJSONObject *GetOrganizationsUUIDMemberships200ApplicationJSON
}
