// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetOrganizationsOrgUUIDInvitationsUUIDRequest struct {
	// The organization’s unique identifier
	OrgUUID string `pathParam:"style=simple,explode=false,name=org_uuid"`
	// The organization invitation's unique identifier
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type GetOrganizationsOrgUUIDInvitationsUUIDErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetOrganizationsOrgUUIDInvitationsUUIDErrorResponse - Error Object
type GetOrganizationsOrgUUIDInvitationsUUIDErrorResponse struct {
	Details []GetOrganizationsOrgUUIDInvitationsUUIDErrorResponseDetails `json:"details,omitempty"`
	Message string                                                       `json:"message"`
	Title   string                                                       `json:"title"`
}

// GetOrganizationsOrgUUIDInvitationsUUID200ApplicationJSON - OK
type GetOrganizationsOrgUUIDInvitationsUUID200ApplicationJSON struct {
	// Organization Invitation object
	Resource shared.OrganizationInvitation `json:"resource"`
}

type GetOrganizationsOrgUUIDInvitationsUUIDResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetOrganizationsOrgUUIDInvitationsUUIDErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetOrganizationsOrgUUIDInvitationsUUID200ApplicationJSONObject *GetOrganizationsOrgUUIDInvitationsUUID200ApplicationJSON
}
