// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetOrganizationMembershipsRequest struct {
	// The number of rows to return
	Count *float64 `queryParam:"style=form,explode=true,name=count"`
	// Indicates if the results should be filtered by email address
	Email *string `queryParam:"style=form,explode=true,name=email"`
	// Indicates if the results should be filtered by organization
	Organization *string `queryParam:"style=form,explode=true,name=organization"`
	// The token to pass to get the next or previous portion of the collection
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Indicates if the results should be filtered by user
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type GetOrganizationMembershipsErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetOrganizationMembershipsErrorResponse - Error Object
type GetOrganizationMembershipsErrorResponse struct {
	Details []GetOrganizationMembershipsErrorResponseDetails `json:"details,omitempty"`
	Message string                                           `json:"message"`
	Title   string                                           `json:"title"`
}

// GetOrganizationMemberships200ApplicationJSON - Service response
type GetOrganizationMemberships200ApplicationJSON struct {
	Collection []shared.OrganizationMembership `json:"collection"`
	Pagination shared.Pagination               `json:"pagination"`
}

type GetOrganizationMembershipsResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetOrganizationMembershipsErrorResponse
	// Caller not authorized to perform this action
	ErrorResponse1 *shared.ErrorResponse
	StatusCode     int
	RawResponse    *http.Response
	// OK
	GetOrganizationMemberships200ApplicationJSONObject *GetOrganizationMemberships200ApplicationJSON
}
