// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetRoutingFormSubmissionsRequest struct {
	// The number of rows to return
	Count *float64 `queryParam:"style=form,explode=true,name=count"`
	// View routing form submissions associated with the routing form's URI.
	Form string `queryParam:"style=form,explode=true,name=form"`
	// The token to pass to get the next or previous portion of the collection
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values. Supported fields are: created_at. Sort direction is specified as: asc, desc.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
}

type GetRoutingFormSubmissionsErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetRoutingFormSubmissionsErrorResponse - Error Object
type GetRoutingFormSubmissionsErrorResponse struct {
	Details []GetRoutingFormSubmissionsErrorResponseDetails `json:"details,omitempty"`
	Message string                                          `json:"message"`
	Title   string                                          `json:"title"`
}

// GetRoutingFormSubmissions200ApplicationJSON - OK
type GetRoutingFormSubmissions200ApplicationJSON struct {
	Collection []shared.RoutingFormSubmission `json:"collection"`
	Pagination shared.Pagination              `json:"pagination"`
}

type GetRoutingFormSubmissionsResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetRoutingFormSubmissionsErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetRoutingFormSubmissions200ApplicationJSONObject *GetRoutingFormSubmissions200ApplicationJSON
}
