// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetRoutingFormsUUIDRequest struct {
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type GetRoutingFormsUUIDErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetRoutingFormsUUIDErrorResponse - Error Object
type GetRoutingFormsUUIDErrorResponse struct {
	Details []GetRoutingFormsUUIDErrorResponseDetails `json:"details,omitempty"`
	Message string                                    `json:"message"`
	Title   string                                    `json:"title"`
}

// GetRoutingFormsUUID200ApplicationJSON - OK
type GetRoutingFormsUUID200ApplicationJSON struct {
	// Information about a routing form.
	Resource shared.RoutingForm `json:"resource"`
}

type GetRoutingFormsUUIDResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetRoutingFormsUUIDErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetRoutingFormsUUID200ApplicationJSONObject *GetRoutingFormsUUID200ApplicationJSON
}
