// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetRoutingFormsRequest struct {
	// The number of rows to return
	Count *float64 `queryParam:"style=form,explode=true,name=count"`
	// View organization routing forms associated with the organization's URI.
	Organization string `queryParam:"style=form,explode=true,name=organization"`
	// The token to pass to get the next or previous portion of the collection
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values. Supported fields are: created_at. Sort direction is specified as: asc, desc.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
}

type GetRoutingFormsErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetRoutingFormsErrorResponse - Error Object
type GetRoutingFormsErrorResponse struct {
	Details []GetRoutingFormsErrorResponseDetails `json:"details,omitempty"`
	Message string                                `json:"message"`
	Title   string                                `json:"title"`
}

// GetRoutingForms200ApplicationJSON - OK
type GetRoutingForms200ApplicationJSON struct {
	Collection []shared.RoutingForm `json:"collection"`
	Pagination shared.Pagination    `json:"pagination"`
}

type GetRoutingFormsResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetRoutingFormsErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetRoutingForms200ApplicationJSONObject *GetRoutingForms200ApplicationJSON
}
