// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetScheduledEventsEventUUIDInviteesInviteeUUIDRequest struct {
	// The event's unique identifier
	EventUUID string `pathParam:"style=simple,explode=false,name=event_uuid"`
	// The invitee's unique identifier
	InviteeUUID string `pathParam:"style=simple,explode=false,name=invitee_uuid"`
}

type GetScheduledEventsEventUUIDInviteesInviteeUUIDErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetScheduledEventsEventUUIDInviteesInviteeUUIDErrorResponse - Error Object
type GetScheduledEventsEventUUIDInviteesInviteeUUIDErrorResponse struct {
	Details []GetScheduledEventsEventUUIDInviteesInviteeUUIDErrorResponseDetails `json:"details,omitempty"`
	Message string                                                               `json:"message"`
	Title   string                                                               `json:"title"`
}

// GetScheduledEventsEventUUIDInviteesInviteeUUID200ApplicationJSON - OK
type GetScheduledEventsEventUUIDInviteesInviteeUUID200ApplicationJSON struct {
	// An individual who has been invited to meet with a Calendly member
	Resource shared.Invitee `json:"resource"`
}

type GetScheduledEventsEventUUIDInviteesInviteeUUIDResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetScheduledEventsEventUUIDInviteesInviteeUUIDErrorResponse
	// Caller not authorized to view event
	ErrorResponse1 *shared.ErrorResponse
	StatusCode     int
	RawResponse    *http.Response
	// OK
	GetScheduledEventsEventUUIDInviteesInviteeUUID200ApplicationJSONObject *GetScheduledEventsEventUUIDInviteesInviteeUUID200ApplicationJSON
}
