// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetUserAvailabilitySchedulesUUIDRequest struct {
	// The UUID of the availability schedule.
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnum string

const (
	GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnumThisUserIsNotInYourOrganization GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnum = "This user is not in your organization"
)

func (e *GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "This user is not in your organization":
		*e = GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnum: %s", s)
	}
}

type GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnum string

const (
	GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnumPermissionDenied GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnum = "Permission Denied"
)

func (e *GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Permission Denied":
		*e = GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnum: %s", s)
	}
}

// GetUserAvailabilitySchedulesUUID403ApplicationJSON - Permission Denied
type GetUserAvailabilitySchedulesUUID403ApplicationJSON struct {
	Message *GetUserAvailabilitySchedulesUUID403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *GetUserAvailabilitySchedulesUUID403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type GetUserAvailabilitySchedulesUUIDErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetUserAvailabilitySchedulesUUIDErrorResponse - Error Object
type GetUserAvailabilitySchedulesUUIDErrorResponse struct {
	Details []GetUserAvailabilitySchedulesUUIDErrorResponseDetails `json:"details,omitempty"`
	Message string                                                 `json:"message"`
	Title   string                                                 `json:"title"`
}

// GetUserAvailabilitySchedulesUUID200ApplicationJSON - OK
type GetUserAvailabilitySchedulesUUID200ApplicationJSON struct {
	// The availability schedule set by the user.
	Resource shared.AvailabilitySchedule `json:"resource"`
}

type GetUserAvailabilitySchedulesUUIDResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetUserAvailabilitySchedulesUUIDErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetUserAvailabilitySchedulesUUID200ApplicationJSONObject *GetUserAvailabilitySchedulesUUID200ApplicationJSON
	// Permission Denied
	GetUserAvailabilitySchedulesUUID403ApplicationJSONObject *GetUserAvailabilitySchedulesUUID403ApplicationJSON
}
