// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type GetUsersUserUUIDWebhooksWebhookUUIDRequest struct {
	WebhookUUID string `pathParam:"style=simple,explode=false,name=webhook_uuid"`
}

type GetUsersUserUUIDWebhooksWebhookUUIDErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetUsersUserUUIDWebhooksWebhookUUIDErrorResponse - Error Object
type GetUsersUserUUIDWebhooksWebhookUUIDErrorResponse struct {
	Details []GetUsersUserUUIDWebhooksWebhookUUIDErrorResponseDetails `json:"details,omitempty"`
	Message string                                                    `json:"message"`
	Title   string                                                    `json:"title"`
}

// GetUsersUserUUIDWebhooksWebhookUUID200ApplicationJSON - OK
type GetUsersUserUUIDWebhooksWebhookUUID200ApplicationJSON struct {
	// Webhook Subscription Object
	Resource shared.WebhookSubscription `json:"resource"`
}

type GetUsersUserUUIDWebhooksWebhookUUIDResponse struct {
	ContentType string
	// Cannot authenticate caller
	ErrorResponse *GetUsersUserUUIDWebhooksWebhookUUIDErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetUsersUserUUIDWebhooksWebhookUUID200ApplicationJSONObject *GetUsersUserUUIDWebhooksWebhookUUID200ApplicationJSON
}
