// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

// GetWebhooksScopeEnum - Filter the list by organization or user
type GetWebhooksScopeEnum string

const (
	GetWebhooksScopeEnumOrganization GetWebhooksScopeEnum = "organization"
	GetWebhooksScopeEnumUser         GetWebhooksScopeEnum = "user"
)

type GetWebhooksQueryParams struct {
	// The number of rows to return
	Count *float64 `queryParam:"style=form,explode=true,name=count"`
	// Indicates if the results should be filtered by organization
	Organization string `queryParam:"style=form,explode=true,name=organization"`
	// The token to pass to get the next or previous portion of the collection
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Filter the list by organization or user
	Scope GetWebhooksScopeEnum `queryParam:"style=form,explode=true,name=scope"`
	// Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values.
	// Supported fields are: created_at.
	// Sort direction is specified as: asc, desc.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Indicates if the results should be filtered by user. This parameter is only required if the `scope` parameter is set to `user`.
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type GetWebhooksRequest struct {
	QueryParams GetWebhooksQueryParams
}

type GetWebhooks403ApplicationJSONMessageEnum string

const (
	GetWebhooks403ApplicationJSONMessageEnumYouDoNotHavePermission                     GetWebhooks403ApplicationJSONMessageEnum = "You do not have permission"
	GetWebhooks403ApplicationJSONMessageEnumYouDoNotHavePermissionToAccessThisResource GetWebhooks403ApplicationJSONMessageEnum = "You do not have permission to access this resource."
	GetWebhooks403ApplicationJSONMessageEnumUnauthorized                               GetWebhooks403ApplicationJSONMessageEnum = "Unauthorized"
)

type GetWebhooks403ApplicationJSONTitleEnum string

const (
	GetWebhooks403ApplicationJSONTitleEnumPermissionDenied GetWebhooks403ApplicationJSONTitleEnum = "Permission Denied"
)

// GetWebhooks403ApplicationJSON - Permission Denied
type GetWebhooks403ApplicationJSON struct {
	Message *GetWebhooks403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *GetWebhooks403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type GetWebhooksErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// GetWebhooksErrorResponse - Error Object
type GetWebhooksErrorResponse struct {
	Details []GetWebhooksErrorResponseDetails `json:"details,omitempty"`
	Message string                            `json:"message"`
	Title   string                            `json:"title"`
}

// GetWebhooks200ApplicationJSON - OK
type GetWebhooks200ApplicationJSON struct {
	Collection []shared.WebhookSubscription `json:"collection"`
	Pagination shared.Pagination            `json:"pagination"`
}

type GetWebhooksResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *GetWebhooksErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	GetWebhooks200ApplicationJSONObject *GetWebhooks200ApplicationJSON
	// Permission Denied
	GetWebhooks403ApplicationJSONObject *GetWebhooks403ApplicationJSON
}
