// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

// ListWebhooksScopeEnum - Filter the list by organization or user
type ListWebhooksScopeEnum string

const (
	ListWebhooksScopeEnumOrganization ListWebhooksScopeEnum = "organization"
	ListWebhooksScopeEnumUser         ListWebhooksScopeEnum = "user"
)

func (e *ListWebhooksScopeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "organization":
		fallthrough
	case "user":
		*e = ListWebhooksScopeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ListWebhooksScopeEnum: %s", s)
	}
}

type ListWebhooksRequest struct {
	// The number of rows to return
	Count *float64 `queryParam:"style=form,explode=true,name=count"`
	// Indicates if the results should be filtered by organization
	Organization string `queryParam:"style=form,explode=true,name=organization"`
	// The token to pass to get the next or previous portion of the collection
	PageToken *string `queryParam:"style=form,explode=true,name=page_token"`
	// Filter the list by organization or user
	Scope ListWebhooksScopeEnum `queryParam:"style=form,explode=true,name=scope"`
	// Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values.
	// Supported fields are: created_at.
	// Sort direction is specified as: asc, desc.
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Indicates if the results should be filtered by user. This parameter is only required if the `scope` parameter is set to `user`.
	User *string `queryParam:"style=form,explode=true,name=user"`
}

type ListWebhooks403ApplicationJSONMessageEnum string

const (
	ListWebhooks403ApplicationJSONMessageEnumYouDoNotHavePermission                     ListWebhooks403ApplicationJSONMessageEnum = "You do not have permission"
	ListWebhooks403ApplicationJSONMessageEnumYouDoNotHavePermissionToAccessThisResource ListWebhooks403ApplicationJSONMessageEnum = "You do not have permission to access this resource."
	ListWebhooks403ApplicationJSONMessageEnumUnauthorized                               ListWebhooks403ApplicationJSONMessageEnum = "Unauthorized"
)

func (e *ListWebhooks403ApplicationJSONMessageEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "You do not have permission":
		fallthrough
	case "You do not have permission to access this resource.":
		fallthrough
	case "Unauthorized":
		*e = ListWebhooks403ApplicationJSONMessageEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ListWebhooks403ApplicationJSONMessageEnum: %s", s)
	}
}

type ListWebhooks403ApplicationJSONTitleEnum string

const (
	ListWebhooks403ApplicationJSONTitleEnumPermissionDenied ListWebhooks403ApplicationJSONTitleEnum = "Permission Denied"
)

func (e *ListWebhooks403ApplicationJSONTitleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Permission Denied":
		*e = ListWebhooks403ApplicationJSONTitleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ListWebhooks403ApplicationJSONTitleEnum: %s", s)
	}
}

// ListWebhooks403ApplicationJSON - Permission Denied
type ListWebhooks403ApplicationJSON struct {
	Message *ListWebhooks403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *ListWebhooks403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type ListWebhooksErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// ListWebhooksErrorResponse - Error Object
type ListWebhooksErrorResponse struct {
	Details []ListWebhooksErrorResponseDetails `json:"details,omitempty"`
	Message string                             `json:"message"`
	Title   string                             `json:"title"`
}

// ListWebhooks200ApplicationJSON - OK
type ListWebhooks200ApplicationJSON struct {
	Collection []shared.WebhookSubscription `json:"collection"`
	Pagination shared.Pagination            `json:"pagination"`
}

type ListWebhooksResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *ListWebhooksErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	ListWebhooks200ApplicationJSONObject *ListWebhooks200ApplicationJSON
	// Permission Denied
	ListWebhooks403ApplicationJSONObject *ListWebhooks403ApplicationJSON
}
