// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type MeErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// MeErrorResponse - Error Object
type MeErrorResponse struct {
	Details []MeErrorResponseDetails `json:"details,omitempty"`
	Message string                   `json:"message"`
	Title   string                   `json:"title"`
}

// Me200ApplicationJSON - Service response
type Me200ApplicationJSON struct {
	// Information about the user.
	Resource shared.User `json:"resource"`
}

type MeResponse struct {
	ContentType string
	// Cannot authenticate caller
	ErrorResponse *MeErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// OK
	Me200ApplicationJSONObject *Me200ApplicationJSON
}
