// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type PostUsersUUIDWebhooksRequestBodyEventsEnum string

const (
	PostUsersUUIDWebhooksRequestBodyEventsEnumInviteeCanceled              PostUsersUUIDWebhooksRequestBodyEventsEnum = "invitee.canceled"
	PostUsersUUIDWebhooksRequestBodyEventsEnumInviteeCreated               PostUsersUUIDWebhooksRequestBodyEventsEnum = "invitee.created"
	PostUsersUUIDWebhooksRequestBodyEventsEnumRoutingFormSubmissionCreated PostUsersUUIDWebhooksRequestBodyEventsEnum = "routing_form_submission.created"
)

// PostUsersUUIDWebhooksRequestBodyScopeEnum - Indicates if the webhook subscription scope will be "organization" or "user"
type PostUsersUUIDWebhooksRequestBodyScopeEnum string

const (
	PostUsersUUIDWebhooksRequestBodyScopeEnumOrganization PostUsersUUIDWebhooksRequestBodyScopeEnum = "organization"
	PostUsersUUIDWebhooksRequestBodyScopeEnumUser         PostUsersUUIDWebhooksRequestBodyScopeEnum = "user"
)

type PostUsersUUIDWebhooksRequestBody struct {
	// List of user events to subscribe to.
	Events []PostUsersUUIDWebhooksRequestBodyEventsEnum `json:"events"`
	// The unique reference to the organization that the webhook will be tied to.
	Organization string `json:"organization"`
	// Indicates if the webhook subscription scope will be "organization" or "user"
	Scope PostUsersUUIDWebhooksRequestBodyScopeEnum `json:"scope"`
	// Optional secret key shared between your application and Calendly. See https://developer.calendly.com/api-docs/ZG9jOjM2MzE2MDM4-webhook-signatures for additional information.
	SigningKey *string `json:"signing_key,omitempty"`
	// The URL where you want to receive POST requests for events you are subscribed to.
	URL string `json:"url"`
	// The unique reference to the user that the webhook will be tied to.
	User *string `json:"user,omitempty"`
}

type PostUsersUUIDWebhooksRequest struct {
	Request PostUsersUUIDWebhooksRequestBody `request:"mediaType=application/json"`
}

type PostUsersUUIDWebhooks403ApplicationJSONMessageEnum string

const (
	PostUsersUUIDWebhooks403ApplicationJSONMessageEnumPleaseUpgradeYourCalendlyAccountToProfessional PostUsersUUIDWebhooks403ApplicationJSONMessageEnum = "Please upgrade your Calendly account to Professional"
	PostUsersUUIDWebhooks403ApplicationJSONMessageEnumYouDoNotHavePermissionToAccessThisResource     PostUsersUUIDWebhooks403ApplicationJSONMessageEnum = "You do not have permission to access this resource."
	PostUsersUUIDWebhooks403ApplicationJSONMessageEnumYouDoNotHavePermission                         PostUsersUUIDWebhooks403ApplicationJSONMessageEnum = "You do not have permission"
)

type PostUsersUUIDWebhooks403ApplicationJSONTitleEnum string

const (
	PostUsersUUIDWebhooks403ApplicationJSONTitleEnumPermissionDenied PostUsersUUIDWebhooks403ApplicationJSONTitleEnum = "Permission Denied"
)

// PostUsersUUIDWebhooks403ApplicationJSON - Permission Denied
type PostUsersUUIDWebhooks403ApplicationJSON struct {
	Message *PostUsersUUIDWebhooks403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *PostUsersUUIDWebhooks403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type PostUsersUUIDWebhooksErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// PostUsersUUIDWebhooksErrorResponse - Error Object
type PostUsersUUIDWebhooksErrorResponse struct {
	Details []PostUsersUUIDWebhooksErrorResponseDetails `json:"details,omitempty"`
	Message string                                      `json:"message"`
	Title   string                                      `json:"title"`
}

// PostUsersUUIDWebhooks201ApplicationJSON - Created
type PostUsersUUIDWebhooks201ApplicationJSON struct {
	// Webhook Subscription Object
	Resource shared.WebhookSubscription `json:"resource"`
}

type PostUsersUUIDWebhooksResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *PostUsersUUIDWebhooksErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// Created
	PostUsersUUIDWebhooks201ApplicationJSONObject *PostUsersUUIDWebhooks201ApplicationJSON
	// Permission Denied
	PostUsersUUIDWebhooks403ApplicationJSONObject *PostUsersUUIDWebhooks403ApplicationJSON
}
