// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type PostScheduledEventsUUIDCancellationPathParams struct {
	// The event's unique indentifier
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type PostScheduledEventsUUIDCancellationMultipartRequest struct {
	PathParams PostScheduledEventsUUIDCancellationPathParams
	// Optional cancellation reason.
	Request map[string]interface{} `request:"mediaType=multipart/form-data"`
}

type PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnum string

const (
	PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnumYouAreNotAllowedToCancelThisEvent PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnum = "You are not allowed to cancel this event"
	PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnumEventInThePast                    PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnum = "Event in the past"
	PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnumEventIsAlreadyCanceled            PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnum = "Event is already canceled"
)

type PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONTitleEnum string

const (
	PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONTitleEnumPermissionDenied PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONTitleEnum = "Permission Denied"
)

// PostScheduledEventsUUIDCancellationMultipart403ApplicationJSON - Caller not authorized to perform this action
type PostScheduledEventsUUIDCancellationMultipart403ApplicationJSON struct {
	Message *PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type PostScheduledEventsUUIDCancellationMultipartErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// PostScheduledEventsUUIDCancellationMultipartErrorResponse - Error Object
type PostScheduledEventsUUIDCancellationMultipartErrorResponse struct {
	Details []PostScheduledEventsUUIDCancellationMultipartErrorResponseDetails `json:"details,omitempty"`
	Message string                                                             `json:"message"`
	Title   string                                                             `json:"title"`
}

// PostScheduledEventsUUIDCancellationMultipart201ApplicationJSON - Created
type PostScheduledEventsUUIDCancellationMultipart201ApplicationJSON struct {
	// Provides data pertaining to the cancellation of the Event
	Resource shared.Cancellation `json:"resource"`
}

type PostScheduledEventsUUIDCancellationMultipartResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *PostScheduledEventsUUIDCancellationMultipartErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// Created
	PostScheduledEventsUUIDCancellationMultipart201ApplicationJSONObject *PostScheduledEventsUUIDCancellationMultipart201ApplicationJSON
	// Caller not authorized to perform this action
	PostScheduledEventsUUIDCancellationMultipart403ApplicationJSONObject *PostScheduledEventsUUIDCancellationMultipart403ApplicationJSON
}
