// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// PostSchedulingLinksRequestBodyMaxEventCountEnum - The max number of events that can be scheduled using this scheduling link.
type PostSchedulingLinksRequestBodyMaxEventCountEnum string

const (
	PostSchedulingLinksRequestBodyMaxEventCountEnumOne PostSchedulingLinksRequestBodyMaxEventCountEnum = "1"
)

func (e *PostSchedulingLinksRequestBodyMaxEventCountEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "1":
		*e = PostSchedulingLinksRequestBodyMaxEventCountEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSchedulingLinksRequestBodyMaxEventCountEnum: %s", s)
	}
}

// PostSchedulingLinksRequestBodyOwnerTypeEnum - Resource type (currently, this is always EventType)
type PostSchedulingLinksRequestBodyOwnerTypeEnum string

const (
	PostSchedulingLinksRequestBodyOwnerTypeEnumEventType PostSchedulingLinksRequestBodyOwnerTypeEnum = "EventType"
)

func (e *PostSchedulingLinksRequestBodyOwnerTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "EventType":
		*e = PostSchedulingLinksRequestBodyOwnerTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSchedulingLinksRequestBodyOwnerTypeEnum: %s", s)
	}
}

type PostSchedulingLinksRequestBody struct {
	// The max number of events that can be scheduled using this scheduling link.
	MaxEventCount PostSchedulingLinksRequestBodyMaxEventCountEnum `json:"max_event_count"`
	// A link to the resource that owns this Scheduling Link (currently, this is always an Event Type)
	Owner string `json:"owner"`
	// Resource type (currently, this is always EventType)
	OwnerType PostSchedulingLinksRequestBodyOwnerTypeEnum `json:"owner_type"`
}

type PostSchedulingLinksRequest struct {
	Request PostSchedulingLinksRequestBody `request:"mediaType=application/json"`
}

type PostSchedulingLinksErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// PostSchedulingLinksErrorResponse - Error Object
type PostSchedulingLinksErrorResponse struct {
	Details []PostSchedulingLinksErrorResponseDetails `json:"details,omitempty"`
	Message string                                    `json:"message"`
	Title   string                                    `json:"title"`
}

// PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum - Resource type (currently, this is always EventType)
type PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum string

const (
	PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnumEventType PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum = "EventType"
)

func (e *PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "EventType":
		*e = PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum: %s", s)
	}
}

type PostSchedulingLinks201ApplicationJSONResource struct {
	// Scheduling link url
	BookingURL string `json:"booking_url"`
	// A link to the resource that owns this Scheduling Link (currently, this is always an Event Type)
	Owner *string `json:"owner,omitempty"`
	// Resource type (currently, this is always EventType)
	OwnerType *PostSchedulingLinks201ApplicationJSONResourceOwnerTypeEnum `json:"owner_type,omitempty"`
}

// PostSchedulingLinks201ApplicationJSON - Created
type PostSchedulingLinks201ApplicationJSON struct {
	Resource PostSchedulingLinks201ApplicationJSONResource `json:"resource"`
}

type PostSchedulingLinksResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *PostSchedulingLinksErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// Created
	PostSchedulingLinks201ApplicationJSONObject *PostSchedulingLinks201ApplicationJSON
}
