// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type PostScheduledEventsUUIDCancellationPathParams struct {
	// The event's unique indentifier
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

// PostScheduledEventsUUIDCancellationApplicationJSON - Optional cancellation reason.
type PostScheduledEventsUUIDCancellationApplicationJSON struct {
	// Reason for cancellation
	Reason *string `json:"reason,omitempty"`
}

type PostScheduledEventsUUIDCancellationJSONRequest struct {
	PathParams PostScheduledEventsUUIDCancellationPathParams
	// Optional cancellation reason.
	Request *PostScheduledEventsUUIDCancellationApplicationJSON `request:"mediaType=application/json"`
}

type PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum string

const (
	PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnumYouAreNotAllowedToCancelThisEvent PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum = "You are not allowed to cancel this event"
	PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnumEventInThePast                    PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum = "Event in the past"
	PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnumEventIsAlreadyCanceled            PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum = "Event is already canceled"
)

func (e *PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "You are not allowed to cancel this event":
		fallthrough
	case "Event in the past":
		fallthrough
	case "Event is already canceled":
		*e = PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum: %s", s)
	}
}

type PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnum string

const (
	PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnumPermissionDenied PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnum = "Permission Denied"
)

func (e *PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Permission Denied":
		*e = PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnum: %s", s)
	}
}

// PostScheduledEventsUUIDCancellationJSON403ApplicationJSON - Caller not authorized to perform this action
type PostScheduledEventsUUIDCancellationJSON403ApplicationJSON struct {
	Message *PostScheduledEventsUUIDCancellationJSON403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *PostScheduledEventsUUIDCancellationJSON403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type PostScheduledEventsUUIDCancellationJSONErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// PostScheduledEventsUUIDCancellationJSONErrorResponse - Error Object
type PostScheduledEventsUUIDCancellationJSONErrorResponse struct {
	Details []PostScheduledEventsUUIDCancellationJSONErrorResponseDetails `json:"details,omitempty"`
	Message string                                                        `json:"message"`
	Title   string                                                        `json:"title"`
}

// PostScheduledEventsUUIDCancellationJSON201ApplicationJSON - Created
type PostScheduledEventsUUIDCancellationJSON201ApplicationJSON struct {
	// Provides data pertaining to the cancellation of the Event
	Resource shared.Cancellation `json:"resource"`
}

type PostScheduledEventsUUIDCancellationJSONResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *PostScheduledEventsUUIDCancellationJSONErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// Created
	PostScheduledEventsUUIDCancellationJSON201ApplicationJSONObject *PostScheduledEventsUUIDCancellationJSON201ApplicationJSON
	// Caller not authorized to perform this action
	PostScheduledEventsUUIDCancellationJSON403ApplicationJSONObject *PostScheduledEventsUUIDCancellationJSON403ApplicationJSON
}
