// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
	"time"
)

// PostDataComplianceDeletionEventsRequestBody - The start and end times that delineate the time range for scheduled events data deletion.
type PostDataComplianceDeletionEventsRequestBody struct {
	// The scheduled events UTC timestamp at which data deletion should end.
	EndTime time.Time `json:"end_time"`
	// The scheduled events UTC timestamp at which data deletion should begin.
	StartTime time.Time `json:"start_time"`
}

type PostDataComplianceDeletionEventsErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// PostDataComplianceDeletionEventsErrorResponse - Error Object
type PostDataComplianceDeletionEventsErrorResponse struct {
	Details []PostDataComplianceDeletionEventsErrorResponseDetails `json:"details,omitempty"`
	Message string                                                 `json:"message"`
	Title   string                                                 `json:"title"`
}

type PostDataComplianceDeletionEventsResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *PostDataComplianceDeletionEventsErrorResponse
	// Forbidden
	ErrorResponse1 *shared.ErrorResponse
	StatusCode     int
	RawResponse    *http.Response
	// Accepted
	PostDataComplianceDeletionEvents202ApplicationJSONObject map[string]interface{}
}
