// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/calendly-go-sdk/pkg/models/shared"
	"net/http"
)

type PostScheduledEventsUUIDCancellationRawRequest struct {
	// Optional cancellation reason.
	RequestBody []byte `request:"mediaType=application/xml"`
	// The event's unique indentifier
	UUID string `pathParam:"style=simple,explode=false,name=uuid"`
}

type PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum string

const (
	PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnumYouAreNotAllowedToCancelThisEvent PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum = "You are not allowed to cancel this event"
	PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnumEventInThePast                    PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum = "Event in the past"
	PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnumEventIsAlreadyCanceled            PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum = "Event is already canceled"
)

func (e *PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "You are not allowed to cancel this event":
		fallthrough
	case "Event in the past":
		fallthrough
	case "Event is already canceled":
		*e = PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum: %s", s)
	}
}

type PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum string

const (
	PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnumPermissionDenied PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum = "Permission Denied"
)

func (e *PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "Permission Denied":
		*e = PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum: %s", s)
	}
}

// PostScheduledEventsUUIDCancellationRaw403ApplicationJSON - Caller not authorized to perform this action
type PostScheduledEventsUUIDCancellationRaw403ApplicationJSON struct {
	Message *PostScheduledEventsUUIDCancellationRaw403ApplicationJSONMessageEnum `json:"message,omitempty"`
	Title   *PostScheduledEventsUUIDCancellationRaw403ApplicationJSONTitleEnum   `json:"title,omitempty"`
}

type PostScheduledEventsUUIDCancellationRawErrorResponseDetails struct {
	Message   string  `json:"message"`
	Parameter *string `json:"parameter,omitempty"`
}

// PostScheduledEventsUUIDCancellationRawErrorResponse - Error Object
type PostScheduledEventsUUIDCancellationRawErrorResponse struct {
	Details []PostScheduledEventsUUIDCancellationRawErrorResponseDetails `json:"details,omitempty"`
	Message string                                                       `json:"message"`
	Title   string                                                       `json:"title"`
}

// PostScheduledEventsUUIDCancellationRaw201ApplicationJSON - Created
type PostScheduledEventsUUIDCancellationRaw201ApplicationJSON struct {
	// Provides data pertaining to the cancellation of the Event
	Resource shared.Cancellation `json:"resource"`
}

type PostScheduledEventsUUIDCancellationRawResponse struct {
	ContentType string
	// Request is not valid
	ErrorResponse *PostScheduledEventsUUIDCancellationRawErrorResponse
	StatusCode    int
	RawResponse   *http.Response
	// Created
	PostScheduledEventsUUIDCancellationRaw201ApplicationJSONObject *PostScheduledEventsUUIDCancellationRaw201ApplicationJSON
	// Caller not authorized to perform this action
	PostScheduledEventsUUIDCancellationRaw403ApplicationJSONObject *PostScheduledEventsUUIDCancellationRaw403ApplicationJSON
}
