// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ActorGroup - User group information about the actor
type ActorGroup struct {
	// Name of the user group
	Name *string `json:"name,omitempty"`
	// The actor's role in the user group
	Role *string `json:"role,omitempty"`
	// Canonical reference (unique identifier) for the user group
	URI *string `json:"uri,omitempty"`
}

type ActorOrganization struct {
	// The actors' role in the organization
	Role *string `json:"role,omitempty"`
	// Canonical reference (unique identifier) for the organization
	URI *string `json:"uri,omitempty"`
}

// Actor - The Calendly actor that took the action creating the activity log entry
//
// Specific actors:
//
// <details>
// <summary>Calendly System</summary>
//
// Used when an action is performed by the Calendly system and not triggered directly by a user interaction.
//
// Example:
// ```json
//
//	{
//	    "display_name": "Calendly System",
//	    "type": "System"
//	}
//
// ```
//
// </details>
//
// <br />
//
// <details>
// <summary>Calendly Support</summary>
// Used when an action is performed by Calendly support.
//
// Example:
// ```json
//
//	{
//	  "display_name": "Calendly Support",
//	  "organization": {
//	    "uri": "https://api.calendly.com/organizations/AAAAAAAAAAAAAAAA"
//	  },
//	  "type": "User",
//	  "uri": "https://api.calendly.com/users/AAAAAAAAAAAAAAAA"
//	}
//
// ```
// </details>
type Actor struct {
	// Username of the actor
	AlternativeIdentifier *string `json:"alternative_identifier,omitempty"`
	// The user's name (human-readable format)
	DisplayName *string `json:"display_name,omitempty"`
	// User group information about the actor
	Group        *ActorGroup        `json:"group,omitempty"`
	Organization *ActorOrganization `json:"organization,omitempty"`
	// The type of actor
	Type string `json:"type"`
	// Canonical reference (unique identifier) for the user
	URI *string `json:"uri,omitempty"`
}
