// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AvailabilitySchedule - The availability schedule set by the user.
type AvailabilitySchedule struct {
	// This is the default Availability Schedule in use.
	Default bool `json:"default"`
	// The name of this Availability Schedule.
	Name string `json:"name"`
	// The rules of this Availability Schedule.
	Rules []AvailabilityRule `json:"rules"`
	// The timezone for which this Availability Schedule is originated in.
	Timezone string `json:"timezone"`
	// A URI reference to this Availability Schedule.
	URI string `json:"uri"`
	// A URI reference to a User.
	User string `json:"user"`
}
