// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CancellationCancelerTypeEnum string

const (
	CancellationCancelerTypeEnumHost    CancellationCancelerTypeEnum = "host"
	CancellationCancelerTypeEnumInvitee CancellationCancelerTypeEnum = "invitee"
)

// Cancellation - Provides data pertaining to the cancellation of the Event
type Cancellation struct {
	// Name of the person whom canceled
	CanceledBy   string                       `json:"canceled_by"`
	CancelerType CancellationCancelerTypeEnum `json:"canceler_type"`
	// Reason that the cancellation occurred
	Reason string `json:"reason"`
}
