// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CustomLocationTypeEnum - The event location doesn't fall into a standard category defined by the event host (publisher)
type CustomLocationTypeEnum string

const (
	CustomLocationTypeEnumCustom CustomLocationTypeEnum = "custom"
)

func (e *CustomLocationTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "custom":
		*e = CustomLocationTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomLocationTypeEnum: %s", s)
	}
}

// CustomLocation - Use this to describe an existing Calendly-supported event location.
type CustomLocation struct {
	// The location description provided by the event host (publisher)
	Location string `json:"location"`
	// The event location doesn't fall into a standard category defined by the event host (publisher)
	Type CustomLocationTypeEnum `json:"type"`
}
