// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Entry - Object for a created activity log record
type Entry struct {
	Action string `json:"action"`
	// The Calendly actor that took the action creating the activity log entry
	//
	// Specific actors:
	//
	// <details>
	// <summary>Calendly System</summary>
	//
	// Used when an action is performed by the Calendly system and not triggered directly by a user interaction.
	//
	// Example:
	// ```json
	// {
	//     "display_name": "Calendly System",
	//     "type": "System"
	// }
	// ```
	//
	// </details>
	//
	// <br />
	//
	// <details>
	// <summary>Calendly Support</summary>
	// Used when an action is performed by Calendly support.
	//
	// Example:
	// ```json
	// {
	//   "display_name": "Calendly Support",
	//   "organization": {
	//     "uri": "https://api.calendly.com/organizations/AAAAAAAAAAAAAAAA"
	//   },
	//   "type": "User",
	//   "uri": "https://api.calendly.com/users/AAAAAAAAAAAAAAAA"
	// }
	// ```
	// </details>
	//
	Actor              *Actor                 `json:"actor,omitempty"`
	Details            map[string]interface{} `json:"details"`
	FullyQualifiedName string                 `json:"fully_qualified_name"`
	Namespace          string                 `json:"namespace"`
	// The date and time of the entry (format: "2020-01-02T03:04:05.678Z").
	OccurredAt   time.Time `json:"occurred_at"`
	Organization string    `json:"organization"`
	URI          string    `json:"uri"`
}
