// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// EventTypeAvailableTime - An available meeting time slot for the given event type
type EventTypeAvailableTime struct {
	// Total remaining invitees for this available time. For Group Event Type, more than one invitee can book in this available time. For all other Event Types, only one invitee can book in this available time.
	InviteesRemaining float64 `json:"invitees_remaining"`
	// The URL of the user’s scheduling site where invitees book this event type
	SchedulingURL string `json:"scheduling_url"`
	// The moment the event was scheduled to start in UTC time
	StartTime time.Time `json:"start_time"`
	// Indicates that the open time slot is "available"
	Status string `json:"status"`
}
