// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// EventTypeCustomQuestionTypeEnum - The type of response that the invitee provides to the custom question; can be one or multiple lines of text, a phone number, or single- or multiple-select.
type EventTypeCustomQuestionTypeEnum string

const (
	EventTypeCustomQuestionTypeEnumString       EventTypeCustomQuestionTypeEnum = "string"
	EventTypeCustomQuestionTypeEnumText         EventTypeCustomQuestionTypeEnum = "text"
	EventTypeCustomQuestionTypeEnumPhoneNumber  EventTypeCustomQuestionTypeEnum = "phone_number"
	EventTypeCustomQuestionTypeEnumSingleSelect EventTypeCustomQuestionTypeEnum = "single_select"
	EventTypeCustomQuestionTypeEnumMultiSelect  EventTypeCustomQuestionTypeEnum = "multi_select"
)

func (e *EventTypeCustomQuestionTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "string":
		fallthrough
	case "text":
		fallthrough
	case "phone_number":
		fallthrough
	case "single_select":
		fallthrough
	case "multi_select":
		*e = EventTypeCustomQuestionTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for EventTypeCustomQuestionTypeEnum: %s", s)
	}
}

type EventTypeCustomQuestion struct {
	// The invitee’s option(s) for single_select or multi_select type of responses.
	AnswerChoices []string `json:"answer_choices"`
	// true if the question created by the host is turned ON and visible on the event booking page; false if turned OFF and invisible on the event booking page.
	Enabled bool `json:"enabled"`
	// true if the custom question lets invitees record a written response in addition to single-select or multiple-select type of responses; false if it doesn’t.
	IncludeOther bool `json:"include_other"`
	// The custom question that the host created for the event type.
	Name string `json:"name"`
	// The numerical position of the question on the event booking page after the name and email address fields.
	Position float64 `json:"position"`
	// true if a response to the question created by the host is required for invitees to book the event type; false if not required.
	Required bool `json:"required"`
	// The type of response that the invitee provides to the custom question; can be one or multiple lines of text, a phone number, or single- or multiple-select.
	Type EventTypeCustomQuestionTypeEnum `json:"type"`
}
