// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// EventTypeBookingMethodEnum - Indicates if the event type is for a poll or an instant booking
type EventTypeBookingMethodEnum string

const (
	EventTypeBookingMethodEnumInstant EventTypeBookingMethodEnum = "instant"
	EventTypeBookingMethodEnumPoll    EventTypeBookingMethodEnum = "poll"
)

// EventTypeKindEnum - Indicates if the event type is "solo" (belongs to an individual user) or "group"
type EventTypeKindEnum string

const (
	EventTypeKindEnumSolo  EventTypeKindEnum = "solo"
	EventTypeKindEnumGroup EventTypeKindEnum = "group"
)

// EventTypeKindDescriptionEnum - A formatted description of the kind of event type.
type EventTypeKindDescriptionEnum string

const (
	EventTypeKindDescriptionEnumCollective EventTypeKindDescriptionEnum = "Collective"
	EventTypeKindDescriptionEnumGroup      EventTypeKindDescriptionEnum = "Group"
	EventTypeKindDescriptionEnumOneOnOne   EventTypeKindDescriptionEnum = "One-on-One"
	EventTypeKindDescriptionEnumRoundRobin EventTypeKindDescriptionEnum = "Round Robin"
)

// EventTypePoolingTypeEnum - Indicates if the event type is "round robin" (alternates between hosts) or "collective" (invitees pick a time when all participants are available) or "null" (the event type doesn’t consider the availability of a group participants)
type EventTypePoolingTypeEnum string

const (
	EventTypePoolingTypeEnumRoundRobin EventTypePoolingTypeEnum = "round_robin"
	EventTypePoolingTypeEnumCollective EventTypePoolingTypeEnum = "collective"
)

// EventTypeTypeEnum - Indicates if the event type is "AdhocEventType" (ad hoc event) or "StandardEventType" (standard event type)
type EventTypeTypeEnum string

const (
	EventTypeTypeEnumStandardEventType EventTypeTypeEnum = "StandardEventType"
	EventTypeTypeEnumAdhocEventType    EventTypeTypeEnum = "AdhocEventType"
)

// EventType - A configuration for an Event
type EventType struct {
	// Indicates if the event is active or not.
	Active bool `json:"active"`
	// Indicates if this event type is managed by an organization admin
	AdminManaged bool `json:"admin_managed"`
	// Indicates if the event type is for a poll or an instant booking
	BookingMethod EventTypeBookingMethodEnum `json:"booking_method"`
	// The hexadecimal color value of the event type's scheduling page
	Color string `json:"color"`
	// The moment the event type was created (e.g. "2020-01-02T03:04:05.678123Z")
	CreatedAt       time.Time                 `json:"created_at"`
	CustomQuestions []EventTypeCustomQuestion `json:"custom_questions"`
	// The moment the event type was deleted (e.g. "2020-01-02T03:04:05.678123Z"). Since event types can be deleted but their scheduled events remain it's useful to fetch a deleted event type when you still require event type data for a scheduled event.
	DeletedAt time.Time `json:"deleted_at"`
	// The event type's description (formatted with HTML)
	DescriptionHTML string `json:"description_html"`
	// The event type's description (in non formatted text)
	DescriptionPlain string `json:"description_plain"`
	// The length of sessions booked with this event type
	Duration float64 `json:"duration"`
	// Contents of a note that may be associated with the event type
	InternalNote string `json:"internal_note"`
	// Indicates if the event type is "solo" (belongs to an individual user) or "group"
	Kind EventTypeKindEnum `json:"kind"`
	// A formatted description of the kind of event type.
	KindDescription EventTypeKindDescriptionEnum `json:"kind_description"`
	// The event type name (in human-readable format)
	Name string `json:"name"`
	// Indicates if the event type is "round robin" (alternates between hosts) or "collective" (invitees pick a time when all participants are available) or "null" (the event type doesn’t consider the availability of a group participants)
	PoolingType EventTypePoolingTypeEnum `json:"pooling_type"`
	// The publicly visible profile of a User or a Team that's associated with the Event Type (note: some Event Types don't have profiles)
	Profile Profile `json:"profile"`
	// The URL of the user’s scheduling site where invitees book this event type
	SchedulingURL string `json:"scheduling_url"`
	// Indicates if the event type is hidden on the owner's main scheduling page
	Secret bool `json:"secret"`
	// The portion of the event type's URL that identifies a specific web page (in a human-readable format)
	Slug string `json:"slug"`
	// Indicates if the event type is "AdhocEventType" (ad hoc event) or "StandardEventType" (standard event type)
	Type EventTypeTypeEnum `json:"type"`
	// The moment the event type was last updated (e.g. "2020-01-02T03:04:05.678123Z")
	UpdatedAt time.Time `json:"updated_at"`
	// Canonical reference (unique identifier) for the event type
	URI string `json:"uri"`
}
