// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GoogleConferenceStatusEnum - Indicates the current status of the Google conference
type GoogleConferenceStatusEnum string

const (
	GoogleConferenceStatusEnumInitiated  GoogleConferenceStatusEnum = "initiated"
	GoogleConferenceStatusEnumProcessing GoogleConferenceStatusEnum = "processing"
	GoogleConferenceStatusEnumPushed     GoogleConferenceStatusEnum = "pushed"
	GoogleConferenceStatusEnumFailed     GoogleConferenceStatusEnum = "failed"
)

// GoogleConferenceTypeEnum - The event location is a Google Meet or Hangouts conference
type GoogleConferenceTypeEnum string

const (
	GoogleConferenceTypeEnumGoogleConference GoogleConferenceTypeEnum = "google_conference"
)

// GoogleConference - Details about an Event that will take place using a Google Meet / Hangout conference
type GoogleConference struct {
	// Google conference meeting url
	JoinURL string `json:"join_url"`
	// Indicates the current status of the Google conference
	Status GoogleConferenceStatusEnum `json:"status"`
	// The event location is a Google Meet or Hangouts conference
	Type GoogleConferenceTypeEnum `json:"type"`
}
