// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// GotoMeetingConferenceData - The conference metadata supplied by GoToMeeting
type GotoMeetingConferenceData struct {
	ConferenceCallInfo *string `json:"conferenceCallInfo,omitempty"`
	// Canonical reference (unique identifier) for the GoToMeeting conference
	UniqueMeetingID *float64 `json:"uniqueMeetingId,omitempty"`
}

// GotoMeetingConferenceStatusEnum - Indicates the current status of the GoToMeeting conference
type GotoMeetingConferenceStatusEnum string

const (
	GotoMeetingConferenceStatusEnumInitiated  GotoMeetingConferenceStatusEnum = "initiated"
	GotoMeetingConferenceStatusEnumProcessing GotoMeetingConferenceStatusEnum = "processing"
	GotoMeetingConferenceStatusEnumPushed     GotoMeetingConferenceStatusEnum = "pushed"
	GotoMeetingConferenceStatusEnumFailed     GotoMeetingConferenceStatusEnum = "failed"
)

func (e *GotoMeetingConferenceStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "initiated":
		fallthrough
	case "processing":
		fallthrough
	case "pushed":
		fallthrough
	case "failed":
		*e = GotoMeetingConferenceStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GotoMeetingConferenceStatusEnum: %s", s)
	}
}

// GotoMeetingConferenceTypeEnum - The event location is a GoToMeeting conference
type GotoMeetingConferenceTypeEnum string

const (
	GotoMeetingConferenceTypeEnumGotomeeting GotoMeetingConferenceTypeEnum = "gotomeeting"
)

func (e *GotoMeetingConferenceTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "gotomeeting":
		*e = GotoMeetingConferenceTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for GotoMeetingConferenceTypeEnum: %s", s)
	}
}

// GotoMeetingConference - Details about an Event that will take place using a GotoMeeting conference
type GotoMeetingConference struct {
	// The conference metadata supplied by GoToMeeting
	Data GotoMeetingConferenceData `json:"data"`
	// GoToMeeting conference meeting url
	JoinURL string `json:"join_url"`
	// Indicates the current status of the GoToMeeting conference
	Status GotoMeetingConferenceStatusEnum `json:"status"`
	// The event location is a GoToMeeting conference
	Type GotoMeetingConferenceTypeEnum `json:"type"`
}
