// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GotoMeetingConferenceData - The conference metadata supplied by GoToMeeting
type GotoMeetingConferenceData struct {
	ConferenceCallInfo *string `json:"conferenceCallInfo,omitempty"`
	// Canonical reference (unique identifier) for the GoToMeeting conference
	UniqueMeetingID *float64 `json:"uniqueMeetingId,omitempty"`
}

// GotoMeetingConferenceStatusEnum - Indicates the current status of the GoToMeeting conference
type GotoMeetingConferenceStatusEnum string

const (
	GotoMeetingConferenceStatusEnumInitiated  GotoMeetingConferenceStatusEnum = "initiated"
	GotoMeetingConferenceStatusEnumProcessing GotoMeetingConferenceStatusEnum = "processing"
	GotoMeetingConferenceStatusEnumPushed     GotoMeetingConferenceStatusEnum = "pushed"
	GotoMeetingConferenceStatusEnumFailed     GotoMeetingConferenceStatusEnum = "failed"
)

// GotoMeetingConferenceTypeEnum - The event location is a GoToMeeting conference
type GotoMeetingConferenceTypeEnum string

const (
	GotoMeetingConferenceTypeEnumGotomeeting GotoMeetingConferenceTypeEnum = "gotomeeting"
)

// GotoMeetingConference - Details about an Event that will take place using a GotoMeeting conference
type GotoMeetingConference struct {
	// The conference metadata supplied by GoToMeeting
	Data GotoMeetingConferenceData `json:"data"`
	// GoToMeeting conference meeting url
	JoinURL string `json:"join_url"`
	// Indicates the current status of the GoToMeeting conference
	Status GotoMeetingConferenceStatusEnum `json:"status"`
	// The event location is a GoToMeeting conference
	Type GotoMeetingConferenceTypeEnum `json:"type"`
}
