// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InboundCallTypeEnum -
// Indicates that the invitee will call the event host
type InboundCallTypeEnum string

const (
	InboundCallTypeEnumInboundCall InboundCallTypeEnum = "inbound_call"
)

func (e *InboundCallTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "inbound_call":
		*e = InboundCallTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for InboundCallTypeEnum: %s", s)
	}
}

// InboundCall - Invitee will call meeting publisher at the specified phone number
type InboundCall struct {
	// The phone number the invitee will use to call the event host (publisher)
	Location string `json:"location"`
	//
	// Indicates that the invitee will call the event host
	Type InboundCallTypeEnum `json:"type"`
}
