// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// InboundCallTypeEnum -
// Indicates that the invitee will call the event host
type InboundCallTypeEnum string

const (
	InboundCallTypeEnumInboundCall InboundCallTypeEnum = "inbound_call"
)

// InboundCall - Invitee will call meeting publisher at the specified phone number
type InboundCall struct {
	// The phone number the invitee will use to call the event host (publisher)
	Location string `json:"location"`
	//
	// Indicates that the invitee will call the event host
	Type InboundCallTypeEnum `json:"type"`
}
