// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// InPersonMeetingTypeEnum - Indicates that the event will be an in-person meeting.
type InPersonMeetingTypeEnum string

const (
	InPersonMeetingTypeEnumPhysical InPersonMeetingTypeEnum = "physical"
)

// InPersonMeeting - Information about the physical (in-person) event location
type InPersonMeeting struct {
	// The physical location specified by the event host (publisher)
	Location string `json:"location"`
	// Indicates that the event will be an in-person meeting.
	Type InPersonMeetingTypeEnum `json:"type"`
}
