// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// InviteeNoShow - Information about an invitees no show.
type InviteeNoShow struct {
	// The moment when the no show was created
	CreatedAt time.Time `json:"created_at"`
	// Canonical reference (unique identifier) for the associated Invitee
	Invitee string `json:"invitee"`
	// Canonical reference (unique identifier) for the no show
	URI string `json:"uri"`
}
