// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InviteeSpecifiedLocationTypeEnum - The event location selected by the invitee
type InviteeSpecifiedLocationTypeEnum string

const (
	InviteeSpecifiedLocationTypeEnumAskInvitee InviteeSpecifiedLocationTypeEnum = "ask_invitee"
)

func (e *InviteeSpecifiedLocationTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "ask_invitee":
		*e = InviteeSpecifiedLocationTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for InviteeSpecifiedLocationTypeEnum: %s", s)
	}
}

// InviteeSpecifiedLocation - Information about an event location that’s specified by the invitee.
type InviteeSpecifiedLocation struct {
	// The event location description provided by the invitee
	Location string `json:"location"`
	// The event location selected by the invitee
	Type InviteeSpecifiedLocationTypeEnum `json:"type"`
}
