// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LegacyCalendarEventKindEnum - Indicates the calendar provider the event belongs to.
type LegacyCalendarEventKindEnum string

const (
	LegacyCalendarEventKindEnumExchange       LegacyCalendarEventKindEnum = "exchange"
	LegacyCalendarEventKindEnumGoogle         LegacyCalendarEventKindEnum = "google"
	LegacyCalendarEventKindEnumIcloud         LegacyCalendarEventKindEnum = "icloud"
	LegacyCalendarEventKindEnumOutlook        LegacyCalendarEventKindEnum = "outlook"
	LegacyCalendarEventKindEnumOutlookDesktop LegacyCalendarEventKindEnum = "outlook_desktop"
)

// LegacyCalendarEvent - Information about the calendar event from the calendar provider.
type LegacyCalendarEvent struct {
	// the id provided from the calendar provider for this calendar event.
	ExternalID string `json:"external_id"`
	// Indicates the calendar provider the event belongs to.
	Kind LegacyCalendarEventKindEnum `json:"kind"`
}
