// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// OrganizationMembershipRoleEnum - The user's role in the organization
type OrganizationMembershipRoleEnum string

const (
	OrganizationMembershipRoleEnumUser  OrganizationMembershipRoleEnum = "user"
	OrganizationMembershipRoleEnumAdmin OrganizationMembershipRoleEnum = "admin"
	OrganizationMembershipRoleEnumOwner OrganizationMembershipRoleEnum = "owner"
)

func (e *OrganizationMembershipRoleEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "user":
		fallthrough
	case "admin":
		fallthrough
	case "owner":
		*e = OrganizationMembershipRoleEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for OrganizationMembershipRoleEnum: %s", s)
	}
}

// OrganizationMembershipUser - Information about the user.
type OrganizationMembershipUser struct {
	// The URL of the user's avatar (image)
	AvatarURL string `json:"avatar_url"`
	// The moment when the user's record was created (e.g. "2020-01-02T03:04:05.678123Z")
	CreatedAt time.Time `json:"created_at"`
	// The user's email address
	Email string `json:"email"`
	// The user's name (human-readable format)
	Name string `json:"name"`
	// The URL of the user's Calendly landing page (that lists all the user's event types)
	SchedulingURL string `json:"scheduling_url"`
	// The portion of URL for the user's scheduling page (where invitees book sessions), rendered in a human-readable format
	Slug string `json:"slug"`
	// The time zone to use when presenting time to the user
	Timezone string `json:"timezone"`
	// The moment when the user's record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
	UpdatedAt time.Time `json:"updated_at"`
	// Canonical reference (unique identifier) for the user
	URI string `json:"uri"`
}

type OrganizationMembership struct {
	// The moment when the membership record was created (e.g. "2020-01-02T03:04:05.678123Z")
	CreatedAt time.Time `json:"created_at"`
	// A unique reference to the organization
	Organization string `json:"organization"`
	// The user's role in the organization
	Role OrganizationMembershipRoleEnum `json:"role"`
	// The moment when the membership record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
	UpdatedAt time.Time `json:"updated_at"`
	// Canonical reference (unique identifier) for the membership
	URI string `json:"uri"`
	// Information about the user.
	User OrganizationMembershipUser `json:"user"`
}
