// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OutboundCallTypeEnum - Indicates that the event host (publisher) will call the invitee
type OutboundCallTypeEnum string

const (
	OutboundCallTypeEnumOutboundCall OutboundCallTypeEnum = "outbound_call"
)

// OutboundCall - Meeting publisher will call the Invitee
type OutboundCall struct {
	// The phone number the event host (publisher) will use to call the invitee
	Location string `json:"location"`
	// Indicates that the event host (publisher) will call the invitee
	Type OutboundCallTypeEnum `json:"type"`
}
