// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OutboundCallTypeEnum - Indicates that the event host (publisher) will call the invitee
type OutboundCallTypeEnum string

const (
	OutboundCallTypeEnumOutboundCall OutboundCallTypeEnum = "outbound_call"
)

func (e *OutboundCallTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "outbound_call":
		*e = OutboundCallTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for OutboundCallTypeEnum: %s", s)
	}
}

// OutboundCall - Meeting publisher will call the Invitee
type OutboundCall struct {
	// The phone number the event host (publisher) will use to call the invitee
	Location string `json:"location"`
	// Indicates that the event host (publisher) will call the invitee
	Type OutboundCallTypeEnum `json:"type"`
}
