// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Pagination struct {
	// The number of rows to return
	Count float64 `json:"count"`
	// URI to return the next page of an ordered list ("null" indicates no additional results are available)
	NextPage string `json:"next_page"`
	// Token to return the next page of an ordered list ("null" indicates no additional results are available)
	NextPageToken string `json:"next_page_token"`
	// URI to return the previous page of an ordered list ("null" indicates no additional results are available)
	PreviousPage string `json:"previous_page"`
	// Token to return the previous page of an ordered list ("null" indicates no additional results are available)
	PreviousPageToken string `json:"previous_page_token"`
}
