// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ProfileTypeEnum - Indicates if the profile belongs to a "user" (individual) or "team"
type ProfileTypeEnum string

const (
	ProfileTypeEnumUser ProfileTypeEnum = "User"
	ProfileTypeEnumTeam ProfileTypeEnum = "Team"
)

// Profile - The publicly visible profile of a User or a Team that's associated with the Event Type (note: some Event Types don't have profiles)
type Profile struct {
	// Human-readable name for the profile of the user that's associated with the event type
	Name string `json:"name"`
	// The unique reference to the user associated with the profile
	Owner string `json:"owner"`
	// Indicates if the profile belongs to a "user" (individual) or "team"
	Type ProfileTypeEnum `json:"type"`
}
