// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// QuestionTypeEnum - Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
type QuestionTypeEnum string

const (
	QuestionTypeEnumName     QuestionTypeEnum = "name"
	QuestionTypeEnumText     QuestionTypeEnum = "text"
	QuestionTypeEnumEmail    QuestionTypeEnum = "email"
	QuestionTypeEnumPhone    QuestionTypeEnum = "phone"
	QuestionTypeEnumTextarea QuestionTypeEnum = "textarea"
	QuestionTypeEnumSelect   QuestionTypeEnum = "select"
	QuestionTypeEnumRadios   QuestionTypeEnum = "radios"
)

// Question - Routing form questions.
type Question struct {
	// The respondent’s option(s) for "select" or "radios" types of questions.
	AnswerChoices []string `json:"answer_choices"`
	// Question name (in human-readable format).
	Name string `json:"name"`
	// true if an answer to the question is required for respondents to submit the routing form; false if not required.
	//
	Required bool `json:"required"`
	// Question type: name, text input, email, phone, textarea input, dropdown list or radio button list.
	Type QuestionTypeEnum `json:"type"`
	// Unique identifier for the routing form question.
	UUID string `json:"uuid"`
}
