// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// RoutingFormStatusEnum - Indicates if the form is in "draft" or "published" status.
type RoutingFormStatusEnum string

const (
	RoutingFormStatusEnumDraft     RoutingFormStatusEnum = "draft"
	RoutingFormStatusEnumPublished RoutingFormStatusEnum = "published"
)

// RoutingForm - Information about a routing form.
type RoutingForm struct {
	// The moment the routing form was created.
	CreatedAt time.Time `json:"created_at"`
	// The routing form name (in human-readable format).
	Name string `json:"name"`
	// The URI of the organization that's associated with the routing form.
	Organization string `json:"organization"`
	// An ordered collection of Routing Form non-deleted questions.
	Questions []Question `json:"questions"`
	// Indicates if the form is in "draft" or "published" status.
	Status RoutingFormStatusEnum `json:"status"`
	// The moment when the routing form was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Canonical reference (unique identifier) for the routing form.
	//
	URI string `json:"uri"`
}
