// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	Oauth2              *string `security:"scheme,type=oauth2,name=Authorization"`
	PersonalAccessToken *string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}
