// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SubmissionTracking - The UTM and Salesforce tracking parameters associated with a Routing Form Submission.
type SubmissionTracking struct {
	// The Salesforce record unique identifier.
	SalesforceUUID string `json:"salesforce_uuid"`
	// The UTM parameter used to track a campaign.
	UtmCampaign string `json:"utm_campaign"`
	// UTM content tracking parameter.
	UtmContent string `json:"utm_content"`
	// The UTM parameter that identifies the type of input (e.g. Cost Per Click (CPC), social media, affiliate or QR code).
	UtmMedium string `json:"utm_medium"`
	// The UTM parameter that identifies the source (platform where the traffic originates).
	UtmSource string `json:"utm_source"`
	// The UTM parameter used to track keywords.
	UtmTerm string `json:"utm_term"`
}
