// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SubmissionEventTypeResultTypeEnum - Indicates that the routing form submission resulted in a redirect to an event type booking page.
type SubmissionEventTypeResultTypeEnum string

const (
	SubmissionEventTypeResultTypeEnumEventType SubmissionEventTypeResultTypeEnum = "event_type"
)

// SubmissionEventTypeResult - Information about the event type Routing Form Submission result.
type SubmissionEventTypeResult struct {
	// Indicates that the routing form submission resulted in a redirect to an event type booking page.
	Type SubmissionEventTypeResultTypeEnum `json:"type"`
	// A reference to the event type resource.
	Value string `json:"value"`
}
