// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SubmissionQuestionAndAnswer - All Routing Form Submission questions with answers.
type SubmissionQuestionAndAnswer struct {
	// Answer provided by the respondent when the form was submitted.
	Answer *string `json:"answer,omitempty"`
	// Question name (in human-readable format).
	Question string `json:"question"`
	// Unique identifier for the routing form question.
	QuestionUUID string `json:"question_uuid"`
}
