// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// SubmissionCustomMessageResultTypeEnum - Indicates if the routing form submission resulted in a custom "thank you" message.
type SubmissionCustomMessageResultTypeEnum string

const (
	SubmissionCustomMessageResultTypeEnumCustomMessage SubmissionCustomMessageResultTypeEnum = "custom_message"
)

func (e *SubmissionCustomMessageResultTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "custom_message":
		*e = SubmissionCustomMessageResultTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SubmissionCustomMessageResultTypeEnum: %s", s)
	}
}

// SubmissionCustomMessageResultValue - Contains an object with custom message headline and body.
type SubmissionCustomMessageResultValue struct {
	// Body text displayed when answers don't match any routes.
	Body string `json:"body"`
	// Headline displayed when answers don't match any routes.
	Headline string `json:"headline"`
}

// SubmissionCustomMessageResult - Information about the custom message Routing Form Submission result.
type SubmissionCustomMessageResult struct {
	// Indicates if the routing form submission resulted in a custom "thank you" message.
	Type SubmissionCustomMessageResultTypeEnum `json:"type"`
	// Contains an object with custom message headline and body.
	Value SubmissionCustomMessageResultValue `json:"value"`
}
