// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// User - Information about the user.
type User struct {
	// The URL of the user's avatar (image)
	AvatarURL string `json:"avatar_url"`
	// The moment when the user's record was created (e.g. "2020-01-02T03:04:05.678123Z")
	CreatedAt time.Time `json:"created_at"`
	// A unique reference to the user's current organization
	CurrentOrganization string `json:"current_organization"`
	// The user's email address
	Email string `json:"email"`
	// The user's name (human-readable format)
	Name string `json:"name"`
	// The URL of the user's Calendly landing page (that lists all the user's event types)
	SchedulingURL string `json:"scheduling_url"`
	// The portion of URL for the user's scheduling page (where invitees book sessions), rendered in a human-readable format
	Slug string `json:"slug"`
	// The time zone to use when presenting time to the user
	Timezone string `json:"timezone"`
	// The moment when the user's record was last updated (e.g. "2020-01-02T03:04:05.678123Z")
	UpdatedAt time.Time `json:"updated_at"`
	// Canonical reference (unique identifier) for the user
	URI string `json:"uri"`
}
