// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WebExConferenceDataTelephonyCallInNumbers struct {
	CallInNumber string `json:"callInNumber"`
	Label        string `json:"label"`
	TollType     string `json:"tollType"`
}

type WebExConferenceDataTelephony struct {
	CallInNumbers []WebExConferenceDataTelephonyCallInNumbers `json:"callInNumbers"`
}

// WebExConferenceData - The conference metadata supplied by GoToMeeting
type WebExConferenceData struct {
	// Canonical reference (unique identifier) for the WebEx conference
	ID        string                       `json:"id"`
	Password  string                       `json:"password"`
	Telephony WebExConferenceDataTelephony `json:"telephony"`
}

// WebExConferenceStatusEnum - Indicates the current status of the WebEx conference
type WebExConferenceStatusEnum string

const (
	WebExConferenceStatusEnumInitiated  WebExConferenceStatusEnum = "initiated"
	WebExConferenceStatusEnumProcessing WebExConferenceStatusEnum = "processing"
	WebExConferenceStatusEnumPushed     WebExConferenceStatusEnum = "pushed"
	WebExConferenceStatusEnumFailed     WebExConferenceStatusEnum = "failed"
)

// WebExConferenceTypeEnum - The event location is a WebEx conference
type WebExConferenceTypeEnum string

const (
	WebExConferenceTypeEnumWebexConference WebExConferenceTypeEnum = "webex_conference"
)

// WebExConference - Details about an Event that will take place using a WebEx conference
type WebExConference struct {
	// The conference metadata supplied by GoToMeeting
	Data WebExConferenceData `json:"data"`
	// WebEx conference meeting url
	JoinURL string `json:"join_url"`
	// Indicates the current status of the WebEx conference
	Status WebExConferenceStatusEnum `json:"status"`
	// The event location is a WebEx conference
	Type WebExConferenceTypeEnum `json:"type"`
}
