// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type WebhookSubscriptionEventsEnum string

const (
	WebhookSubscriptionEventsEnumInviteeCreated               WebhookSubscriptionEventsEnum = "invitee.created"
	WebhookSubscriptionEventsEnumInviteeCanceled              WebhookSubscriptionEventsEnum = "invitee.canceled"
	WebhookSubscriptionEventsEnumRoutingFormSubmissionCreated WebhookSubscriptionEventsEnum = "routing_form_submission.created"
)

// WebhookSubscriptionScopeEnum - The scope of the webhook subscription
type WebhookSubscriptionScopeEnum string

const (
	WebhookSubscriptionScopeEnumUser         WebhookSubscriptionScopeEnum = "user"
	WebhookSubscriptionScopeEnumOrganization WebhookSubscriptionScopeEnum = "organization"
)

// WebhookSubscriptionStateEnum - Indicates if the webhook subscription is "active" or "disabled"
type WebhookSubscriptionStateEnum string

const (
	WebhookSubscriptionStateEnumActive   WebhookSubscriptionStateEnum = "active"
	WebhookSubscriptionStateEnumDisabled WebhookSubscriptionStateEnum = "disabled"
)

// WebhookSubscription - Webhook Subscription Object
type WebhookSubscription struct {
	// The callback URL to use when the event is triggered
	CallbackURL string `json:"callback_url"`
	// The moment when the webhook subscription was created (e.g. "2020-01-02T03:04:05.678123Z")
	CreatedAt time.Time `json:"created_at"`
	// The URI of the user who created the webhook subscription
	Creator string `json:"creator"`
	// A list of events to which the webhook is subscribed
	Events []WebhookSubscriptionEventsEnum `json:"events"`
	// The URI of the organization that's associated with the webhook subscription
	Organization string `json:"organization"`
	// The date and time the webhook subscription is retried
	RetryStartedAt time.Time `json:"retry_started_at"`
	// The scope of the webhook subscription
	Scope WebhookSubscriptionScopeEnum `json:"scope"`
	// Indicates if the webhook subscription is "active" or "disabled"
	State WebhookSubscriptionStateEnum `json:"state"`
	// The moment when the webhook subscription was last updated (e.g. "2020-01-02T03:04:05.678123Z")
	UpdatedAt time.Time `json:"updated_at"`
	// Canonical reference (unique identifier) for the webhook
	URI string `json:"uri"`
	// The URI of the user that's associated with the webhook subscription
	User string `json:"user"`
}
